all: popen1 popen3 pipe1 pipe2 pipe3 pipe4

popen1: popen1.c
	gcc popen1.c -o popen1

popen3: popen3.c
	gcc popen3.c -o popen3


pipe1: pipe1.c
	gcc pipe1.c -o pipe1

pipe2: pipe2.c
	gcc pipe2.c -o pipe2

pipe3: pipe3.c
	gcc pipe3.c -o pipe3

pipe4: pipe4.c
	gcc pipe4.c -o pipe4